const token_brow="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmRjNjljYmE3NjU3ZmQ0ZDc0OWY5NCIsImVtYWlsIjoidGVzdEBnLmNvbSIsImlhdCI6MTcyNjIxNDk5NiwiZXhwIjoxNzI2ODE5Nzk2fQ.6BM3AljjK1Ftdg5MmKfJHY7Q0tau-fqnpbgMLOrtcJI"
const token_mongo="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmRjNjljYmE3NjU3ZmQ0ZDc0OWY5NCIsImVtYWlsIjoidGVzdEBnLmNvbSIsImlhdCI6MTcyNjIxNTIxMSwiZXhwIjoxNzI2ODIwMDExfQ.Mr1lZIVETZxGXq23zru4RClYraqVqyRFLCCjJDMv1Lk"

console.log(token_brow==token_mongo);
